version: '3.8'

services:
  # PHP-FPM Service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: winter-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - winter

  # Nginx Service
  web:
    image: nginx:1.25
    container_name: winter-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - winter
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: winter-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: winter
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: winter
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - winter-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - winter

  # Valkey Service (Redis fork)
  valkey:
    image: valkey/valkey:latest
    container_name: winter-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - winter-valkey:/data
    networks:
      - winter

networks:
  winter:
    driver: bridge

volumes:
  winter-mysql:
    driver: local
  winter-valkey:
    driver: local